# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/adip/catkin_ws/src/gi_healthcare/ui/userInterface.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 760)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(480, 760))
        Form.setMaximumSize(QtCore.QSize(480, 800))
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.screens = QtWidgets.QTabWidget(Form)
        self.screens.setGeometry(QtCore.QRect(0, -50, 481, 831))
        self.screens.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.screens.setObjectName("screens")
        self.firstScreen = QtWidgets.QWidget()
        self.firstScreen.setObjectName("firstScreen")
        self.label = QtWidgets.QLabel(self.firstScreen)
        self.label.setGeometry(QtCore.QRect(30, 110, 421, 261))
        self.label.setStyleSheet("background-image: url(:/newPrefix/Images/logo/GIHealthcareLogo.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/Images/logo/GIHealthcareLogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.firstScreen)
        self.label_2.setGeometry(QtCore.QRect(0, 420, 471, 101))
        font = QtGui.QFont()
        font.setFamily("URW Chancery L")
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.firstScreen)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 560, 471, 102))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.startButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.startButton.setMinimumSize(QtCore.QSize(300, 100))
        self.startButton.setMaximumSize(QtCore.QSize(300, 100))
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 40px;\n"
"    border-color: beige;\n"
"    font: bold 48px;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.shutdownButton = QtWidgets.QPushButton(self.firstScreen)
        self.shutdownButton.setGeometry(QtCore.QRect(390, 30, 71, 61))
        self.shutdownButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/icons/shutdown.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shutdownButton.setIcon(icon)
        self.shutdownButton.setIconSize(QtCore.QSize(50, 50))
        self.shutdownButton.setObjectName("shutdownButton")
        self.screens.addTab(self.firstScreen, "")
        self.secondScreen = QtWidgets.QWidget()
        self.secondScreen.setObjectName("secondScreen")
        self.label_3 = QtWidgets.QLabel(self.secondScreen)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 341, 281))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/Images/icons/secondIcon.jpg);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/Images/icons/secondIcon.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.secondScreen)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 460, 471, 102))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.customDishButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.customDishButton.setMinimumSize(QtCore.QSize(300, 100))
        self.customDishButton.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.customDishButton.setFont(font)
        self.customDishButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 40px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.customDishButton.setObjectName("customDishButton")
        self.horizontalLayout_3.addWidget(self.customDishButton)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.secondScreen)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 610, 471, 102))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.availableCuisinesButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.availableCuisinesButton.setMinimumSize(QtCore.QSize(300, 100))
        self.availableCuisinesButton.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.availableCuisinesButton.setFont(font)
        self.availableCuisinesButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 40px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.availableCuisinesButton.setObjectName("availableCuisinesButton")
        self.horizontalLayout_4.addWidget(self.availableCuisinesButton)
        self.back2_1Button = QtWidgets.QPushButton(self.secondScreen)
        self.back2_1Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back2_1Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back2_1Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back2_1Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/icons/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back2_1Button.setIcon(icon1)
        self.back2_1Button.setIconSize(QtCore.QSize(40, 40))
        self.back2_1Button.setObjectName("back2_1Button")
        self.screens.addTab(self.secondScreen, "")
        self.inventoryScreen = QtWidgets.QWidget()
        self.inventoryScreen.setObjectName("inventoryScreen")
        self.back31_2Button = QtWidgets.QPushButton(self.inventoryScreen)
        self.back31_2Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back31_2Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back31_2Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back31_2Button.setText("")
        self.back31_2Button.setIcon(icon1)
        self.back31_2Button.setIconSize(QtCore.QSize(40, 40))
        self.back31_2Button.setObjectName("back31_2Button")
        self.label_4 = QtWidgets.QLabel(self.inventoryScreen)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.inventory = QtWidgets.QToolBox(self.inventoryScreen)
        self.inventory.setGeometry(QtCore.QRect(10, 130, 451, 551))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inventory.setFont(font)
        self.inventory.setObjectName("inventory")
        self.vegetables = QtWidgets.QWidget()
        self.vegetables.setGeometry(QtCore.QRect(0, 0, 451, 440))
        self.vegetables.setObjectName("vegetables")
        self.gridLayoutWidget = QtWidgets.QWidget(self.vegetables)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 451, 421))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.potatoButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.potatoButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/vegetable/potato.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.potatoButton.setIcon(icon2)
        self.potatoButton.setIconSize(QtCore.QSize(150, 150))
        self.potatoButton.setCheckable(True)
        self.potatoButton.setObjectName("potatoButton")
        self.gridLayout.addWidget(self.potatoButton, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 1, 1, 1)
        self.onionButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.onionButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/vegetable/onion.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.onionButton.setIcon(icon3)
        self.onionButton.setIconSize(QtCore.QSize(150, 150))
        self.onionButton.setCheckable(True)
        self.onionButton.setObjectName("onionButton")
        self.gridLayout.addWidget(self.onionButton, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.garlicButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.garlicButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/vegetable/garlic.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.garlicButton.setIcon(icon4)
        self.garlicButton.setIconSize(QtCore.QSize(150, 150))
        self.garlicButton.setCheckable(True)
        self.garlicButton.setObjectName("garlicButton")
        self.gridLayout.addWidget(self.garlicButton, 2, 0, 1, 1)
        self.tomatoButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.tomatoButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tomatoButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/vegetable/tomato.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tomatoButton.setIcon(icon5)
        self.tomatoButton.setIconSize(QtCore.QSize(150, 150))
        self.tomatoButton.setCheckable(True)
        self.tomatoButton.setObjectName("tomatoButton")
        self.gridLayout.addWidget(self.tomatoButton, 2, 1, 1, 1)
        self.inventory.addItem(self.vegetables, "")
        self.meat = QtWidgets.QWidget()
        self.meat.setGeometry(QtCore.QRect(0, 0, 451, 440))
        self.meat.setObjectName("meat")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.meat)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 451, 421))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.turkeyButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.turkeyButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.turkeyButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/meat/turkey.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turkeyButton.setIcon(icon6)
        self.turkeyButton.setIconSize(QtCore.QSize(150, 150))
        self.turkeyButton.setCheckable(True)
        self.turkeyButton.setObjectName("turkeyButton")
        self.gridLayout_2.addWidget(self.turkeyButton, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.porkButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.porkButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Images/meat/pork.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.porkButton.setIcon(icon7)
        self.porkButton.setIconSize(QtCore.QSize(150, 150))
        self.porkButton.setCheckable(True)
        self.porkButton.setObjectName("porkButton")
        self.gridLayout_2.addWidget(self.porkButton, 2, 0, 1, 1)
        self.fishButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.fishButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Images/meat/fis.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fishButton.setIcon(icon8)
        self.fishButton.setIconSize(QtCore.QSize(150, 150))
        self.fishButton.setCheckable(True)
        self.fishButton.setObjectName("fishButton")
        self.gridLayout_2.addWidget(self.fishButton, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 1, 1, 1)
        self.chickenButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.chickenButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Images/meat/chick.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chickenButton.setIcon(icon9)
        self.chickenButton.setIconSize(QtCore.QSize(150, 150))
        self.chickenButton.setCheckable(True)
        self.chickenButton.setObjectName("chickenButton")
        self.gridLayout_2.addWidget(self.chickenButton, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.inventory.addItem(self.meat, "")
        self.dairyEggs = QtWidgets.QWidget()
        self.dairyEggs.setGeometry(QtCore.QRect(0, 0, 451, 440))
        self.dairyEggs.setObjectName("dairyEggs")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.dairyEggs)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 10, 451, 421))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 3, 0, 1, 1)
        self.creamButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.creamButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.creamButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Images/dairyEgg/cream.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.creamButton.setIcon(icon10)
        self.creamButton.setIconSize(QtCore.QSize(150, 150))
        self.creamButton.setCheckable(True)
        self.creamButton.setObjectName("creamButton")
        self.gridLayout_4.addWidget(self.creamButton, 2, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 1, 1, 1)
        self.butterButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.butterButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Images/dairyEgg/butter.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butterButton.setIcon(icon11)
        self.butterButton.setIconSize(QtCore.QSize(150, 150))
        self.butterButton.setCheckable(True)
        self.butterButton.setObjectName("butterButton")
        self.gridLayout_4.addWidget(self.butterButton, 2, 0, 1, 1)
        self.eggButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.eggButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Images/dairyEgg/egg.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eggButton.setIcon(icon12)
        self.eggButton.setIconSize(QtCore.QSize(150, 150))
        self.eggButton.setCheckable(True)
        self.eggButton.setObjectName("eggButton")
        self.gridLayout_4.addWidget(self.eggButton, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 3, 1, 1, 1)
        self.milkButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.milkButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Images/dairyEgg/milk.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.milkButton.setIcon(icon13)
        self.milkButton.setIconSize(QtCore.QSize(150, 150))
        self.milkButton.setCheckable(True)
        self.milkButton.setObjectName("milkButton")
        self.gridLayout_4.addWidget(self.milkButton, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.inventory.addItem(self.dairyEggs, "")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.inventoryScreen)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 690, 471, 61))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.continueCustomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.continueCustomButton.setMinimumSize(QtCore.QSize(200, 50))
        self.continueCustomButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.continueCustomButton.setFont(font)
        self.continueCustomButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.continueCustomButton.setObjectName("continueCustomButton")
        self.horizontalLayout_5.addWidget(self.continueCustomButton)
        self.screens.addTab(self.inventoryScreen, "")
        self.allergyScreen = QtWidgets.QWidget()
        self.allergyScreen.setObjectName("allergyScreen")
        self.back31_4Button = QtWidgets.QPushButton(self.allergyScreen)
        self.back31_4Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back31_4Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back31_4Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back31_4Button.setText("")
        self.back31_4Button.setIcon(icon1)
        self.back31_4Button.setIconSize(QtCore.QSize(40, 40))
        self.back31_4Button.setObjectName("back31_4Button")
        self.label_21 = QtWidgets.QLabel(self.allergyScreen)
        self.label_21.setGeometry(QtCore.QRect(10, 90, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.allergyScreen)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 690, 471, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.continueAllergyButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.continueAllergyButton.setMinimumSize(QtCore.QSize(200, 50))
        self.continueAllergyButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.continueAllergyButton.setFont(font)
        self.continueAllergyButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.continueAllergyButton.setObjectName("continueAllergyButton")
        self.horizontalLayout_6.addWidget(self.continueAllergyButton)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.allergyScreen)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(110, 140, 271, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.peanuts = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.peanuts.setFont(font)
        self.peanuts.setObjectName("peanuts")
        self.verticalLayout.addWidget(self.peanuts)
        self.milk = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.milk.setFont(font)
        self.milk.setObjectName("milk")
        self.verticalLayout.addWidget(self.milk)
        self.seaFood = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.seaFood.setFont(font)
        self.seaFood.setObjectName("seaFood")
        self.verticalLayout.addWidget(self.seaFood)
        self.wheat = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.wheat.setFont(font)
        self.wheat.setObjectName("wheat")
        self.verticalLayout.addWidget(self.wheat)
        self.eggs = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.eggs.setFont(font)
        self.eggs.setObjectName("eggs")
        self.verticalLayout.addWidget(self.eggs)
        self.noAllergy = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(21)
        self.noAllergy.setFont(font)
        self.noAllergy.setObjectName("noAllergy")
        self.verticalLayout.addWidget(self.noAllergy)
        self.screens.addTab(self.allergyScreen, "")
        self.chatGPTScreen = QtWidgets.QWidget()
        self.chatGPTScreen.setObjectName("chatGPTScreen")
        self.label_22 = QtWidgets.QLabel(self.chatGPTScreen)
        self.label_22.setGeometry(QtCore.QRect(10, 90, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.back4_5Button = QtWidgets.QPushButton(self.chatGPTScreen)
        self.back4_5Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back4_5Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back4_5Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back4_5Button.setText("")
        self.back4_5Button.setIcon(icon1)
        self.back4_5Button.setIconSize(QtCore.QSize(40, 40))
        self.back4_5Button.setObjectName("back4_5Button")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.chatGPTScreen)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 690, 471, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.startCustomButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.startCustomButton.setMinimumSize(QtCore.QSize(200, 50))
        self.startCustomButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.startCustomButton.setFont(font)
        self.startCustomButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.startCustomButton.setObjectName("startCustomButton")
        self.horizontalLayout_7.addWidget(self.startCustomButton)
        self.chatGPTSuggestion = QtWidgets.QPlainTextEdit(self.chatGPTScreen)
        self.chatGPTSuggestion.setGeometry(QtCore.QRect(10, 140, 461, 541))
        font = QtGui.QFont()
        font.setFamily("Tibetan Machine Uni")
        font.setPointSize(15)
        self.chatGPTSuggestion.setFont(font)
        self.chatGPTSuggestion.setPlainText("")
        self.chatGPTSuggestion.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.chatGPTSuggestion.setObjectName("chatGPTSuggestion")
        self.screens.addTab(self.chatGPTScreen, "")
        self.availableDishScreen = QtWidgets.QWidget()
        self.availableDishScreen.setObjectName("availableDishScreen")
        self.label_23 = QtWidgets.QLabel(self.availableDishScreen)
        self.label_23.setGeometry(QtCore.QRect(10, 90, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.back32_2Button = QtWidgets.QPushButton(self.availableDishScreen)
        self.back32_2Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back32_2Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back32_2Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back32_2Button.setText("")
        self.back32_2Button.setIcon(icon1)
        self.back32_2Button.setIconSize(QtCore.QSize(40, 40))
        self.back32_2Button.setObjectName("back32_2Button")
        self.scrollArea = QtWidgets.QScrollArea(self.availableDishScreen)
        self.scrollArea.setGeometry(QtCore.QRect(10, 160, 461, 561))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 459, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, -30, 461, 251))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.noodleButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.noodleButton.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Images/foodPics/noodles.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.noodleButton.setIcon(icon14)
        self.noodleButton.setIconSize(QtCore.QSize(200, 200))
        self.noodleButton.setCheckable(True)
        self.noodleButton.setObjectName("noodleButton")
        self.horizontalLayout_8.addWidget(self.noodleButton)
        self.friedOnionButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.friedOnionButton.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Images/foodPics/friedOnions.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.friedOnionButton.setIcon(icon15)
        self.friedOnionButton.setIconSize(QtCore.QSize(200, 200))
        self.friedOnionButton.setCheckable(True)
        self.friedOnionButton.setObjectName("friedOnionButton")
        self.horizontalLayout_8.addWidget(self.friedOnionButton)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.screens.addTab(self.availableDishScreen, "")
        self.noodleScreen = QtWidgets.QWidget()
        self.noodleScreen.setObjectName("noodleScreen")
        self.back1_7Button = QtWidgets.QPushButton(self.noodleScreen)
        self.back1_7Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back1_7Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back1_7Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back1_7Button.setText("")
        self.back1_7Button.setIcon(icon1)
        self.back1_7Button.setIconSize(QtCore.QSize(40, 40))
        self.back1_7Button.setObjectName("back1_7Button")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.noodleScreen)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 690, 471, 61))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.startNoodlesCookButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.startNoodlesCookButton.setMinimumSize(QtCore.QSize(200, 50))
        self.startNoodlesCookButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.startNoodlesCookButton.setFont(font)
        self.startNoodlesCookButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.startNoodlesCookButton.setObjectName("startNoodlesCookButton")
        self.horizontalLayout_9.addWidget(self.startNoodlesCookButton)
        self.label_24 = QtWidgets.QLabel(self.noodleScreen)
        self.label_24.setGeometry(QtCore.QRect(10, 90, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.label_13 = QtWidgets.QLabel(self.noodleScreen)
        self.label_13.setGeometry(QtCore.QRect(110, 150, 261, 241))
        self.label_13.setStyleSheet("background-image: url(:/newPrefix/Images/foodPics/noodles.jpg);")
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/newPrefix/Images/foodPics/noodles.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.noodleScreen)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 450, 451, 211))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_14 = QtWidgets.QLabel(self.noodleScreen)
        self.label_14.setGeometry(QtCore.QRect(10, 390, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.screens.addTab(self.noodleScreen, "")
        self.vegetableChopping = QtWidgets.QWidget()
        self.vegetableChopping.setObjectName("vegetableChopping")
        self.label_25 = QtWidgets.QLabel(self.vegetableChopping)
        self.label_25.setGeometry(QtCore.QRect(10, 90, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.back32_7Button = QtWidgets.QPushButton(self.vegetableChopping)
        self.back32_7Button.setGeometry(QtCore.QRect(10, 30, 70, 51))
        self.back32_7Button.setMinimumSize(QtCore.QSize(70, 0))
        self.back32_7Button.setMaximumSize(QtCore.QSize(70, 16777215))
        self.back32_7Button.setText("")
        self.back32_7Button.setIcon(icon1)
        self.back32_7Button.setIconSize(QtCore.QSize(40, 40))
        self.back32_7Button.setObjectName("back32_7Button")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.vegetableChopping)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 690, 471, 61))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.vegeSlotContiueButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.vegeSlotContiueButton.setMinimumSize(QtCore.QSize(200, 50))
        self.vegeSlotContiueButton.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.vegeSlotContiueButton.setFont(font)
        self.vegeSlotContiueButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.vegeSlotContiueButton.setObjectName("vegeSlotContiueButton")
        self.horizontalLayout_12.addWidget(self.vegeSlotContiueButton)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.vegetableChopping)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(40, 160, 401, 161))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_16.setMinimumSize(QtCore.QSize(150, 150))
        self.label_16.setMaximumSize(QtCore.QSize(150, 150))
        self.label_16.setStyleSheet("background-image: url(:/newPrefix/Images/vegetable/onion.jpg);")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/newPrefix/Images/vegetable/onion.jpg"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_26.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_2.addWidget(self.label_26)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.choppingMode = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.choppingMode.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.choppingMode.setFont(font)
        self.choppingMode.setObjectName("choppingMode")
        self.horizontalLayout.addWidget(self.choppingMode)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.screens.addTab(self.vegetableChopping, "")
        self.cookingScreen = QtWidgets.QWidget()
        self.cookingScreen.setObjectName("cookingScreen")
        self.cookingStatus = QtWidgets.QLabel(self.cookingScreen)
        self.cookingStatus.setGeometry(QtCore.QRect(10, 40, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.cookingStatus.setFont(font)
        self.cookingStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.cookingStatus.setObjectName("cookingStatus")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.cookingScreen)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 690, 471, 61))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.startWashButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.startWashButton.setMinimumSize(QtCore.QSize(300, 50))
        self.startWashButton.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.startWashButton.setFont(font)
        self.startWashButton.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 157, 112);\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(216, 131, 95);\n"
"    border-style: inset;\n"
"}")
        self.startWashButton.setObjectName("startWashButton")
        self.horizontalLayout_11.addWidget(self.startWashButton)
        self.label_15 = QtWidgets.QLabel(self.cookingScreen)
        self.label_15.setGeometry(QtCore.QRect(80, 120, 311, 311))
        self.label_15.setStyleSheet("background-image: url(:/newPrefix/Images/icons/cooking.png);")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/newPrefix/Images/icons/cooking.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.cookingProgress = QtWidgets.QProgressBar(self.cookingScreen)
        self.cookingProgress.setGeometry(QtCore.QRect(10, 470, 461, 71))
        self.cookingProgress.setProperty("value", 24)
        self.cookingProgress.setObjectName("cookingProgress")
        self.screens.addTab(self.cookingScreen, "")
        self.shutdownScreen = QtWidgets.QWidget()
        self.shutdownScreen.setObjectName("shutdownScreen")
        self.label_27 = QtWidgets.QLabel(self.shutdownScreen)
        self.label_27.setGeometry(QtCore.QRect(20, 120, 421, 261))
        font = QtGui.QFont()
        font.setFamily("Abyssinica SIL")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.shutdownScreen)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(50, 310, 371, 102))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.shutdownYes = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.shutdownYes.setMinimumSize(QtCore.QSize(150, 50))
        self.shutdownYes.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shutdownYes.setFont(font)
        self.shutdownYes.setObjectName("shutdownYes")
        self.horizontalLayout_10.addWidget(self.shutdownYes)
        spacerItem = QtWidgets.QSpacerItem(214, 75, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.shutdownNo = QtWidgets.QPushButton(self.horizontalLayoutWidget_12)
        self.shutdownNo.setMinimumSize(QtCore.QSize(150, 50))
        self.shutdownNo.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.shutdownNo.setFont(font)
        self.shutdownNo.setObjectName("shutdownNo")
        self.horizontalLayout_10.addWidget(self.shutdownNo)
        self.screens.addTab(self.shutdownScreen, "")

        self.retranslateUi(Form)
        self.screens.setCurrentIndex(9)
        self.inventory.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Beyond The Palate’s Limits"))
        self.startButton.setText(_translate("Form", "Start"))
        self.screens.setTabText(self.screens.indexOf(self.firstScreen), _translate("Form", "firstScreen"))
        self.customDishButton.setText(_translate("Form", "Custom Dish"))
        self.availableCuisinesButton.setText(_translate("Form", "Available Dish"))
        self.screens.setTabText(self.screens.indexOf(self.secondScreen), _translate("Form", "secondScreen"))
        self.label_4.setText(_translate("Form", "What\'s in your inventory ?"))
        self.label_5.setText(_translate("Form", "Onion"))
        self.label_8.setText(_translate("Form", "Tomato"))
        self.label_6.setText(_translate("Form", "Potato"))
        self.label_7.setText(_translate("Form", "Garlic"))
        self.inventory.setItemText(self.inventory.indexOf(self.vegetables), _translate("Form", "Vegetables"))
        self.label_12.setText(_translate("Form", "Pork"))
        self.label_11.setText(_translate("Form", "Fish"))
        self.label_10.setText(_translate("Form", "Turkey"))
        self.label_9.setText(_translate("Form", "Chicken"))
        self.inventory.setItemText(self.inventory.indexOf(self.meat), _translate("Form", "Meat"))
        self.label_17.setText(_translate("Form", "Butter"))
        self.label_18.setText(_translate("Form", "Egg"))
        self.label_19.setText(_translate("Form", "Cream"))
        self.label_20.setText(_translate("Form", "Cow Milk"))
        self.inventory.setItemText(self.inventory.indexOf(self.dairyEggs), _translate("Form", "Dairy and Egg"))
        self.continueCustomButton.setText(_translate("Form", "Continue"))
        self.screens.setTabText(self.screens.indexOf(self.inventoryScreen), _translate("Form", "inventoryScreen"))
        self.label_21.setText(_translate("Form", "What\'s your allergy ?"))
        self.continueAllergyButton.setText(_translate("Form", "Continue"))
        self.peanuts.setText(_translate("Form", "      Peanuts"))
        self.milk.setText(_translate("Form", "      Milk"))
        self.seaFood.setText(_translate("Form", "      Sea food"))
        self.wheat.setText(_translate("Form", "      Wheat"))
        self.eggs.setText(_translate("Form", "      Eggs"))
        self.noAllergy.setText(_translate("Form", "      No Allergy"))
        self.screens.setTabText(self.screens.indexOf(self.allergyScreen), _translate("Form", "allergyScreen"))
        self.label_22.setText(_translate("Form", "Recommended Recipe"))
        self.startCustomButton.setText(_translate("Form", "Start"))
        self.screens.setTabText(self.screens.indexOf(self.chatGPTScreen), _translate("Form", "chatGPTScreen"))
        self.label_23.setText(_translate("Form", "Available Dishes"))
        self.screens.setTabText(self.screens.indexOf(self.availableDishScreen), _translate("Form", "availableDishScreen"))
        self.startNoodlesCookButton.setText(_translate("Form", "Continue"))
        self.label_24.setText(_translate("Form", "Noodles"))
        self.plainTextEdit.setPlainText(_translate("Form", "Noodles are food made from wheat, rice, or other grains. Noodles are low in calories and fat and are a good source of carbohydrates. They also contain some protein, vitamins, and minerals. Noodles made from whole grains, such as whole wheat or brown rice, are healthier because they are higher in fibre and nutrients."))
        self.label_14.setText(_translate("Form", "Description"))
        self.screens.setTabText(self.screens.indexOf(self.noodleScreen), _translate("Form", "noodleScreen"))
        self.label_25.setText(_translate("Form", "Assigned slot for ingredients"))
        self.vegeSlotContiueButton.setText(_translate("Form", "Continue"))
        self.label_26.setText(_translate("Form", "Slot 1"))
        self.screens.setTabText(self.screens.indexOf(self.vegetableChopping), _translate("Form", "vegetableChopping"))
        self.cookingStatus.setText(_translate("Form", "Start Cooking"))
        self.startWashButton.setText(_translate("Form", "Start Washing"))
        self.screens.setTabText(self.screens.indexOf(self.cookingScreen), _translate("Form", "cookingScreen"))
        self.label_27.setText(_translate("Form", "Shutdown System ?"))
        self.shutdownYes.setText(_translate("Form", "Yes"))
        self.shutdownNo.setText(_translate("Form", "No"))
        self.screens.setTabText(self.screens.indexOf(self.shutdownScreen), _translate("Form", "shutdownScreen"))

import images_rc
